version: "3.3"

services:
  app:
    build: .
    command: sh -c "npm run build && npm run db:reload && npm run start"
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - ".:/usr/app"
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "240191"
      MYSQL_DATABASE: "hurb"
  adminer:
    image: adminer
    restart: always    
    ports:      
      - "8080:8080"