version: "3.3"

services:
  app:
    command: sh -c "npm run build && npm run migration:revert default && npm run migration:run default && npm run fixture:run && npm run start"
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: "240191"
      MYSQL_DATABASE: "hurb"