version: "3.3"

services:
  app:
    command: sh -c "npm run build && npm run migration:revert test && npm run migration:run test && npm run test"
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: "240191"
      MYSQL_DATABASE: "hurbtest"